style = "default"
indent = 4
margin = 92
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
import_to_using = true
remove_extra_newlines = true
short_to_long_function_def = true
# always_use_return = true
